#!/bin/sh

sysmodmap=/etc/X11/xinit/.Xmodmap
usermodmap=$HOME/.config/X11/Xmodmap

sysresources=/etc/X11/xinit/.Xresources
userresources=$HOME/.config/X11/Xresources
pywalresources=$HOME/.cache/wal/colors.Xresources

export SUDO_ASKPASS="/usr/local/bin/askpass"
export THISX_TTY=$(tty)
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export TWORLDSAVEDIR="$XDG_DATA_HOME"/tworld/

# merge in defaults and keymaps

[ -f $sysresources ] &&
    xrdb -merge $sysresources

[ -f $sysmodmap ] &&
    xmodmap $sysmodmap

[ -f "$userresources" ] &&
    xrdb -merge "$userresources"

[ -f "$usermodmap" ] &&
    xmodmap "$usermodmap"

[ -f $pywalresources ] &&
    xrdb -merge "$pywalresources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

sxhkd &
# picom --experimental-backends & #--transparent-clipping &
picom &
mpd &
~/.fehbg

statusbar &
xinput disable "$(xinput | grep TouchPad | grep -o "id=\S*" | cut -d'=' -f2)"

exec startdwm
