#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

exec 2>/dev/null

magick identify -format "%wx%h | %f | %[size] | %[magick] | %[colorspace] %[compression] %[quality]\n" "$1"
