# shellcheck shell=bash
# shellcheck source=/dev/null

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=""
HISTFILESIZE=""

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    linux|dvtm|xterm-color|*-256color) color_prompt=yes;;
esac

exitstatus()
{
# shellcheck disable=SC2181
    if [[ $? == 0 ]]; then
        echo -e '\001\e[1;32m\002✔'
    else
        echo -e '\001\e[1;31m\002x'
    fi
}
if [ "$color_prompt" = yes ]; then
    PS1='\[\e[1;34m\]|$(exitstatus)\[\e[1;32m\]\u@\h\[\e(B\e[m\]:\[\e[1;35m\]\w\[\e[1;34m\]|\[\e[36m\]\$\[\e(B\e[m\] '
    PS2='\[\e[36m\]>\[\e[0m\] '
else
    PS1='[\u@\h \w]\$ '
fi
unset color_prompt

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
# shellcheck disable=SC2015
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
[ -f ~/.config/bash/aliases ] &&
   . ~/.config/bash/aliases

[ -f ~/.config/bash/functions ] &&
   . ~/.config/bash/functions

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

## disable C-s, C-q
stty -ixon
